apiVersion: v1
kind: Service
metadata:
  name: sjgx-platform
  namespace: sjgx-dev
spec:
  type: ClusterIP
  selector:
    app: sjgx-platform
  ports:
    - name: http
      port: 8080
      targetPort: 8080
